"""Data-only LTX-2 contribution to the global configuration registry."""

from __future__ import annotations

from pathlib import Path

from kinomlx.cli.config_records import (
    AUDIO_CODEC_CHOICES,
    CUT_DETECT_MODE_CHOICES,
    VSR_SPATIAL_MODE_CHOICES,
    VSR_TEMPORAL_MODE_CHOICES,
    OutputConfig,
)
from kinomlx.cli.config_schema import settings_table
from kinomlx.cli.restart import LATENT_STAGE_CHOICES, RESTART_PHASE_CHOICES, RestartConfig
from kinomlx.config import (
    ConfigFieldSpec,
    ConfigGroup,
    ConfigImplication,
    ConfigTableSpec,
    ModelConfigSpec,
)
from kinomlx.models.ltx2.artifacts import LTX2ArtifactConfig
from kinomlx.models.ltx2.settings import (
    GEMMA_VARIANT_CHOICES,
    MODEL_GENERATION_CHOICES,
    STREAM_TRANSFORMER_COMPILE_GROUP_SIZE,
    STREAM_TRANSFORMER_RESIDENT_BLOCKS,
    TRANSFORMER_CACHE_QUANTIZE_CHOICES,
    TRANSFORMER_DTYPE_CHOICES,
    VIDEO_VAE_CHOICES,
    LTX2Settings,
)
from kinomlx.models.ltx2.types import (
    DISTILLED_SAMPLER_CHOICES,
    HDR_AUTHORING_CHOICES,
    LORA_EXCLUDE_CATEGORIES,
    VAE_DECODE_DTYPE_CHOICES,
    VAE_TILING_MODE_CHOICES,
    DistilledRequest,
    HDRReferenceConditioningConfig,
    ImageConditioningConfig,
    VideoVAETilingConfig,
)
from kinomlx.types import NOISE_BACKEND_CHOICES

F = ConfigFieldSpec
_RESTART_DECODE = frozenset({ConfigGroup.RESTART_DECODE_LOCKED})
_RESTART_BOTH = frozenset(
    {
        ConfigGroup.RESTART_DECODE_LOCKED,
        ConfigGroup.RESTART_STAGE2_LOCKED,
    }
)


CONFIG_SCHEMA = ModelConfigSpec(
    model="ltx2",
    title="KinoMLX LTX-2 starter configuration",
    introduction=(
        "The prompt below is the only non-default starter value.",
        (
            "Every other setting is commented out so KinoMLX can use its built-in "
            "default or an environment variable. Uncomment only the settings you "
            "want to override."
        ),
    ),
    root_fields=(
        F(
            name="model",
            purpose="Select the invocation schema",
            valid="",
            choices=("ltx2",),
            example="ltx2",
            starter="ltx2",
            cli_dest="model",
            virtual=True,
            default="ltx2",
        ),
    ),
    tables=(
        ConfigTableSpec(
            path=("generate",),
            record=DistilledRequest,
            nested=("image", "hdr_reference", "vae_tiling"),
            fields=(
                F(
                    "prompt",
                    "Describe the video to generate",
                    "any string",
                    "Describe your video here.",
                    cli_dest="prompt",
                    starter="Describe your video here.",
                    multiline=True,
                    strip=True,
                    groups=_RESTART_BOTH,
                ),
                F(
                    "width",
                    "Set the output width in pixels",
                    "a positive multiple of 64",
                    1024,
                    cli_dest="width",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "height",
                    "Set the output height in pixels",
                    "a positive multiple of 64",
                    576,
                    cli_dest="height",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "frames",
                    "Set the output frame count",
                    "a positive integer matching 8*k + 1",
                    121,
                    cli_dest="frames",
                    notes=("Do not combine this with duration or auto_duration in the same layer",),
                    groups=_RESTART_BOTH,
                ),
                F(
                    "duration",
                    "Set the duration instead of setting the frame count",
                    "a finite number of seconds greater than 0",
                    5.0,
                    cli_dest="duration",
                    notes=("Do not combine this with frames or auto_duration in the same layer",),
                    groups=_RESTART_BOTH,
                ),
                F(
                    "auto_duration",
                    "Let the checkpoint duration head choose the duration",
                    "true or false",
                    True,
                    cli_dest="auto_duration",
                    virtual=True,
                    default=False,
                    notes=("Do not combine this with frames or duration in the same layer",),
                ),
                F(
                    "fps",
                    "Set the generation frame rate",
                    "a finite number greater than 0",
                    24.0,
                    cli_dest="fps",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "seed",
                    "Set the random seed",
                    "an integer from 0 through 2**64 - 1",
                    42,
                    cli_dest="seed",
                    stringify_large_int=True,
                ),
                F(
                    "noise_backend",
                    "Select the normal-noise stream",
                    "",
                    "mlx",
                    cli_dest="noise_backend",
                    choices=NOISE_BACKEND_CHOICES,
                    choice_help=(
                        ("mlx", "Use KinoMLX's native MLX normal-noise stream"),
                        ("torch-mps", "Match the pinned PyTorch MPS normal-noise stream"),
                    ),
                ),
                F(
                    "sampler",
                    "Select the stage-1 sampler policy",
                    "",
                    "auto",
                    cli_dest="sampler",
                    choices=DISTILLED_SAMPLER_CHOICES,
                    choice_help=(
                        ("auto", "Use the checkpoint generation's published policy"),
                        ("deterministic", "Use deterministic stage-1 sampling"),
                        ("ancestral", "Use ancestral stage-1 sampling"),
                    ),
                    groups=_RESTART_BOTH,
                ),
                F(
                    "hdr",
                    "Select an HDR authoring profile",
                    "",
                    "SRGB_LINEAR",
                    cli_dest="hdr",
                    choices=HDR_AUTHORING_CHOICES,
                    choice_help=(
                        ("SRGB_LINEAR", "Write scene-linear Rec.709 EXR masters"),
                        ("ACESCG", "Write scene-linear ACEScg EXR masters"),
                        ("ACESCCT", "Write ACEScct working-space EXR masters"),
                    ),
                    default_text="unset, which produces SDR output",
                ),
                F(
                    "generate_audio",
                    "Generate the joint audio branch",
                    "true or false",
                    False,
                    cli_dest="generate_audio",
                    negative_purpose="Disable the joint audio branch",
                ),
                F(
                    "reference_aligned_audio",
                    "Use the reference implementation's rounded audio length",
                    "true or false",
                    False,
                    cli_dest="reference_aligned_audio",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "generated_keyframes",
                    "Reserve stage-1 slots for generated keyframes",
                    "a non-negative integer",
                    0,
                    cli_dest="generated_keyframes",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "text_conditioning",
                    "Load saved prompt tensors instead of running Gemma",
                    "a path to a compatible safetensors file",
                    Path("prompt_text.safetensors"),
                    cli_dest="text_conditioning",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "vae_decode_dtype",
                    "Select the VAE decode precision",
                    "",
                    "auto",
                    cli_dest="vae_decode_dtype",
                    choices=VAE_DECODE_DTYPE_CHOICES,
                    choice_help=(
                        ("auto", "Use bfloat16 for SDR and float32 for HDR"),
                        ("bfloat16", "Force bfloat16 VAE decode compute"),
                        ("float32", "Force float32 VAE decode compute"),
                    ),
                ),
                F(
                    "pad_prompt_to_max",
                    "Pad Gemma input to 1,024 tokens",
                    "true or false",
                    True,
                    cli_dest="pad_prompt_to_max",
                    negative_purpose="Use variable-length Gemma input without maximum padding",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "lora_paths",
                    "Apply community LoRA adapters in order",
                    "an array of paths to compatible safetensors files",
                    (Path("adapter.safetensors"),),
                    cli_dest="lora_paths",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "lora_strengths",
                    "Set the total adapter weights",
                    "one finite value or one per LoRA",
                    (1.0,),
                    cli_dest="lora_strengths",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "lora_stage1_strengths",
                    "Set stage-1 adapter weights",
                    "one finite value or one per LoRA",
                    (1.0,),
                    cli_dest="lora_stage1_strengths",
                    groups=_RESTART_BOTH,
                ),
                F(
                    "lora_stage2_strengths",
                    "Set stage-2 adapter weights",
                    "one finite value or one per LoRA",
                    (1.0,),
                    cli_dest="lora_stage2_strengths",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "lora_exclusions",
                    "Disable selected adapter categories for each LoRA",
                    "one category string or one string per LoRA; categories: "
                    + ", ".join(sorted(LORA_EXCLUDE_CATEGORIES)),
                    ("audio",),
                    cli_dest="lora_exclusions",
                    groups=_RESTART_DECODE,
                ),
            ),
        ),
        ConfigTableSpec(
            path=("generate", "image"),
            record=ImageConditioningConfig,
            starter_enabled=False,
            default_present=False,
            introduction=(
                "Optional image conditioning. Uncomment this table header and the "
                "fields you want to set."
            ),
            fields=(
                F(
                    "path",
                    "Set the image-conditioning source",
                    "a readable image path",
                    Path("input.png"),
                    cli_dest="image",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "frame_index",
                    "Choose the conditioned output frame",
                    "a non-negative integer",
                    0,
                    cli_dest="image_frame_index",
                ),
                F(
                    "strength",
                    "Set the image-conditioning strength",
                    "a number from 0 through 1",
                    0.95,
                    cli_dest="image_strength",
                ),
            ),
        ),
        ConfigTableSpec(
            path=("generate", "hdr_reference"),
            record=HDRReferenceConditioningConfig,
            starter_enabled=False,
            default_present=False,
            introduction=(
                "Optional LTX-2.3 SDR reference conditioning. Uncomment this table "
                "header and the fields you want to set."
            ),
            fields=(
                F(
                    "path",
                    "Set the SDR reference video",
                    "a readable video path",
                    Path("reference.mov"),
                    cli_dest="hdr_reference",
                    groups=_RESTART_DECODE,
                ),
                F(
                    "strength",
                    "Set the SDR reference strength",
                    "a number from 0 through 1",
                    1.0,
                    cli_dest="hdr_reference_strength",
                ),
            ),
        ),
        ConfigTableSpec(
            path=("generate", "vae_tiling"),
            record=VideoVAETilingConfig,
            starter_enabled=False,
            introduction=(
                "Optional VAE decode tiling. Uncomment this table header and the "
                "fields you want to set."
            ),
            fields=(
                F(
                    "mode",
                    "Select the decode tiling policy",
                    "",
                    "custom",
                    cli_dest="vae_tiling",
                    choices=VAE_TILING_MODE_CHOICES,
                    choice_help=(
                        ("auto", "Let the decoder choose a memory-aware tiling plan"),
                        ("single", "Decode the complete latent in one operation"),
                        ("custom", "Use the temporal and spatial tile fields below"),
                    ),
                ),
                F(
                    "temporal_tile_frames",
                    "Set the temporal tile size",
                    "0, or a multiple of 8 that is at least 16",
                    32,
                    cli_dest="vae_temporal_tile_frames",
                    default_text="unset, or 256 when the mode is custom",
                ),
                F(
                    "temporal_overlap_frames",
                    "Set the temporal overlap",
                    "a non-negative multiple of 8 smaller than the temporal tile",
                    24,
                    cli_dest="vae_temporal_overlap_frames",
                ),
                F(
                    "spatial_tile_pixels",
                    "Set the spatial tile size",
                    "0, or a multiple of 32 that is at least 64",
                    512,
                    cli_dest="vae_spatial_tile_pixels",
                ),
                F(
                    "spatial_overlap_pixels",
                    "Set the spatial overlap",
                    "a non-negative multiple of 32 smaller than the spatial tile",
                    64,
                    cli_dest="vae_spatial_overlap_pixels",
                ),
            ),
        ),
        ConfigTableSpec(
            path=("output",),
            record=OutputConfig,
            fields=(
                F(
                    "path",
                    "Write to an exact video path",
                    "a path string",
                    Path("video.mp4"),
                    cli_dest="output_path",
                    default_text="unset, which creates a timestamped output",
                ),
                F(
                    "directory",
                    "Choose the directory for timestamped output",
                    "a directory path",
                    Path("outputs"),
                    cli_dest="output_dir",
                    default_text='KINO_OUTPUT_DIR, then "outputs"',
                ),
                F(
                    "prefix",
                    "Set the timestamped filename prefix",
                    "non-empty filename text",
                    "kinomlx",
                    cli_dest="output_prefix",
                ),
                F(
                    "vsr_spatial_mode",
                    "Select the spatial VSR mode",
                    "",
                    "off",
                    cli_dest="vsr_spatial_mode",
                    choices=VSR_SPATIAL_MODE_CHOICES,
                    choice_help=(
                        ("off", "Disable spatial super-resolution"),
                        ("fast", "Use the low-latency spatial processor"),
                        ("balanced", "Use temporally aware balanced-quality VSR"),
                        ("image", "Use the highest-quality per-frame spatial processor"),
                    ),
                ),
                F(
                    "target_fps",
                    "Set the post-generation frame rate",
                    "a finite number greater than 0",
                    48.0,
                    cli_dest="target_fps",
                ),
                F(
                    "vsr_temporal_mode",
                    "Select the temporal interpolation quality",
                    "",
                    "normal",
                    cli_dest="vsr_temporal_mode",
                    choices=VSR_TEMPORAL_MODE_CHOICES,
                    choice_help=(
                        ("normal", "Use normal-quality frame interpolation"),
                        ("high", "Use high-quality frame interpolation"),
                    ),
                ),
                F(
                    "cut_detect_mode",
                    "Select hard-cut protection",
                    "",
                    "simple",
                    cli_dest="cut_detect_mode",
                    choices=CUT_DETECT_MODE_CHOICES,
                    choice_help=(
                        ("off", "Disable hard-cut protection"),
                        ("simple", "Use the default lightweight cut detector"),
                        ("hist", "Use histogram detection for motion-heavy footage"),
                    ),
                ),
                F(
                    "cut_detect_threshold",
                    "Override the cut detector threshold",
                    "a finite number greater than or equal to 0",
                    0.35,
                    cli_dest="cut_detect_threshold",
                ),
                F(
                    "vsr_save_original",
                    "Keep the preprocessed video beside the VSR output",
                    "true or false",
                    False,
                    cli_dest="vsr_save_original",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "encode_quality",
                    "Set VideoToolbox encoding quality",
                    "a number from 0 through 1",
                    0.65,
                    cli_dest="encode_quality",
                ),
                F(
                    "audio_codec",
                    "Select the encoded audio codec",
                    "",
                    "alac",
                    cli_dest="audio_codec",
                    choices=AUDIO_CODEC_CHOICES,
                    choice_help=(
                        ("alac", "Encode lossless Apple Lossless audio"),
                        ("aac", "Encode compact lossy AAC audio"),
                    ),
                ),
                F(
                    "audio_onset_trim",
                    "Configure audio onset repair",
                    '"auto", "off", or a non-negative millisecond value',
                    "auto",
                    cli_dest="audio_onset_trim",
                ),
                F(
                    "save_run_log",
                    "Save the resolved invocation and timing as JSON",
                    "true or false",
                    False,
                    cli_dest="save_run_log",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_console_log",
                    "Save a human-readable execution log",
                    "true or false",
                    False,
                    cli_dest="save_console_log",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_effective_config",
                    "Save the effective invocation as a TOML sidecar",
                    "true or false",
                    False,
                    cli_dest="save_effective_config",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_audio_sidecar",
                    "Save generated audio as a WAV sidecar",
                    "true or false",
                    False,
                    cli_dest="save_audio_sidecar",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_hdr_heic_frames",
                    "Save HDR frames as PQ HEIC files",
                    "true or false",
                    False,
                    cli_dest="save_hdr_heic_frames",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_vae_frames",
                    "Save normalized pre-postprocess PNG frames",
                    "true or false",
                    False,
                    cli_dest="save_vae_frames",
                    groups=frozenset({ConfigGroup.SAVE_ALL_CANDIDATE}),
                ),
                F(
                    "save_all_sidecars",
                    "Enable every applicable reproducibility sidecar",
                    "true or false",
                    False,
                    cli_dest="save_all_sidecars",
                ),
            ),
        ),
        settings_table(),
        ConfigTableSpec(
            path=("model_settings",),
            record=LTX2Settings,
            fields=(
                F(
                    "model_generation",
                    "Select the checkpoint generation",
                    "",
                    "2.3",
                    cli_dest="model_generation",
                    choices=MODEL_GENERATION_CHOICES,
                    choice_help=(
                        ("2.3", "Discover and run the LTX-2.3 checkpoint family"),
                        ("2.5", "Discover and run the LTX-2.5 checkpoint family"),
                    ),
                    default_text="unset, which uses 2.3 discovery",
                    groups=frozenset({ConfigGroup.MODEL_GENERATION_SELECTOR}),
                ),
                F(
                    "weights_path",
                    "Load a monolithic baseline or use an LTX-2.5 pack as the component root",
                    "a compatible safetensors file or local LTX-2.5 pack directory",
                    Path("ltx-2.3.safetensors"),
                    cli_dest="weights_path",
                    default_text="unset or KINO_WEIGHTS_PATH",
                    groups=frozenset(
                        {
                            ConfigGroup.MODEL_SOURCE,
                            ConfigGroup.MODEL_MONOLITHIC_SOURCE,
                        }
                    ),
                ),
                F(
                    "gemma_path",
                    "Load a monolithic Gemma checkpoint",
                    "a path to a compatible safetensors file",
                    Path("gemma.safetensors"),
                    cli_dest="gemma_path",
                    default_text="auto-discovered",
                    groups=frozenset(
                        {
                            ConfigGroup.MODEL_SOURCE,
                            ConfigGroup.MODEL_GEMMA_SOURCE,
                        }
                    ),
                ),
                F(
                    "gemma_variant",
                    "Select the LTX-2.3 Gemma source",
                    "",
                    "qat",
                    cli_dest="gemma_variant",
                    choices=GEMMA_VARIANT_CHOICES,
                    choice_help=(
                        ("qat", "Use the QAT-unquantized Gemma source paired with LTX-2.3"),
                        ("plain", "Use the plain instruction-tuned Gemma source"),
                    ),
                ),
                F(
                    "spatial_upscaler_path",
                    "Load the spatial latent upscaler",
                    "a path to a compatible safetensors file",
                    Path("spatial-upscaler.safetensors"),
                    cli_dest="spatial_upscaler_path",
                    default_text="auto-discovered",
                    groups=frozenset({ConfigGroup.MODEL_SOURCE}),
                ),
                F(
                    "transformer_path",
                    "Load a componentized transformer or override the baseline transformer",
                    "a directory or safetensors path",
                    Path("transformer/"),
                    cli_dest="transformer_path",
                    groups=frozenset(
                        {
                            ConfigGroup.MODEL_SOURCE,
                            ConfigGroup.MODEL_SPLIT_SOURCE,
                        }
                    ),
                ),
                F(
                    "text_encoder_path",
                    "Load a componentized text stack",
                    "a directory or safetensors path",
                    Path("text-encoder/"),
                    cli_dest="text_encoder_path",
                    groups=frozenset(
                        {
                            ConfigGroup.MODEL_SOURCE,
                            ConfigGroup.MODEL_TEXT_ENCODER_SOURCE,
                        }
                    ),
                ),
                F(
                    "video_vae",
                    "Select the named video decoder",
                    "",
                    "conv",
                    cli_dest="video_vae",
                    choices=VIDEO_VAE_CHOICES,
                    choice_help=(
                        ("conv", "Use the convolutional video VAE"),
                        ("diffusion", "Use the compatible LTX-2.5 diffusion decoder"),
                    ),
                    groups=frozenset({ConfigGroup.MODEL_VIDEO_VAE_SELECTOR}),
                ),
                F(
                    "video_vae_path",
                    "Load an explicit video VAE",
                    "a directory or safetensors path",
                    Path("video-vae/"),
                    cli_dest="video_vae_path",
                    default_text="auto-discovered",
                    groups=frozenset(
                        {
                            ConfigGroup.MODEL_SOURCE,
                            ConfigGroup.MODEL_VIDEO_VAE_SOURCE,
                        }
                    ),
                ),
                F(
                    "audio_vae_path",
                    "Load an explicit audio VAE and vocoder",
                    "a directory or safetensors path",
                    Path("audio-vae/"),
                    cli_dest="audio_vae_path",
                    default_text="auto-discovered",
                    groups=frozenset({ConfigGroup.MODEL_SOURCE}),
                ),
                F(
                    "temporal_latent_upscaler_path",
                    "Load the temporal x2 latent upscaler",
                    "a path to a compatible safetensors file",
                    Path("temporal-upscaler.safetensors"),
                    cli_dest="temporal_latent_upscaler_path",
                    default_text="auto-discovered",
                    groups=frozenset({ConfigGroup.MODEL_SOURCE}),
                ),
                F(
                    "duration_head_path",
                    "Load the automatic-duration head",
                    "a path to a compatible safetensors file",
                    Path("duration-head.safetensors"),
                    cli_dest="duration_head_path",
                    default_text="auto-discovered",
                    groups=frozenset({ConfigGroup.MODEL_SOURCE}),
                ),
                F(
                    "fast_mode",
                    "Build one full lazy transformer graph",
                    "true or false",
                    True,
                    cli_dest="fast_mode",
                ),
                F(
                    "transformer_dtype",
                    "Select transformer storage and compute precision",
                    "",
                    "bfloat16",
                    cli_dest="transformer_dtype",
                    choices=TRANSFORMER_DTYPE_CHOICES,
                    choice_help=(
                        ("bfloat16", "Use bfloat16 transformer storage and compute"),
                        ("float16", "Use float16 transformer storage and compute"),
                        ("float32", "Use float32 transformer storage and compute"),
                    ),
                ),
                F(
                    "steel_attention",
                    "Enable eligible STEEL attention kernels",
                    "true or false",
                    True,
                    cli_dest="steel_attention",
                ),
                F(
                    "steel_attention_d64",
                    "Enable the head-dimension-64 STEEL path",
                    "true or false",
                    True,
                    cli_dest="steel_attention_d64",
                ),
                F(
                    "steel_attention_probe",
                    "Collect STEEL selection diagnostics",
                    "true or false when STEEL attention is enabled",
                    False,
                    cli_dest="steel_attention_probe",
                ),
                F(
                    "compile_attention",
                    "Compile eligible attention calls",
                    "true or false",
                    True,
                    cli_dest="compile_attention",
                ),
                F(
                    "video_ff_layout_specs",
                    "Configure video feed-forward cache layouts",
                    ('unique "project_in:pretranspose" or "project_out:pretranspose" entries'),
                    ("project_out:pretranspose",),
                    cli_dest="video_ff_layout_specs",
                ),
                F(
                    "video_ff_layout_layers",
                    "Choose video layers for feed-forward cache layouts",
                    "unique integers from 0 through 47",
                    (),
                    cli_dest="video_ff_layout_layers",
                ),
                F(
                    "video_attn_layout_specs",
                    "Configure video attention cache layouts",
                    'unique attention-target entries ending in ":pretranspose"',
                    (),
                    cli_dest="video_attn_layout_specs",
                ),
                F(
                    "video_attn_layout_layers",
                    "Choose video layers for attention cache layouts",
                    "unique integers from 0 through 47",
                    (),
                    cli_dest="video_attn_layout_layers",
                ),
                F(
                    "audio_layout_mirror",
                    "Mirror video cache layouts to audio blocks",
                    "true or false",
                    True,
                    cli_dest="audio_layout_mirror",
                ),
                F(
                    "audio_ff_layout_specs",
                    "Configure audio feed-forward cache layouts",
                    'unique feed-forward target entries ending in ":pretranspose"',
                    (),
                    cli_dest="audio_ff_layout_specs",
                ),
                F(
                    "audio_ff_layout_layers",
                    "Choose audio layers for feed-forward cache layouts",
                    "unique integers from 0 through 47",
                    (),
                    cli_dest="audio_ff_layout_layers",
                ),
                F(
                    "audio_attn_layout_specs",
                    "Configure audio attention cache layouts",
                    'unique attention-target entries ending in ":pretranspose"',
                    (),
                    cli_dest="audio_attn_layout_specs",
                ),
                F(
                    "audio_attn_layout_layers",
                    "Choose audio layers for attention cache layouts",
                    "unique integers from 0 through 47",
                    (),
                    cli_dest="audio_attn_layout_layers",
                ),
                F(
                    "adaln_pretranspose",
                    "Pretranspose AdaLN cache tensors",
                    "true or false",
                    False,
                    cli_dest="adaln_pretranspose",
                ),
                F(
                    "transformer_cache_quantize",
                    "Select whole-cache quantization",
                    "",
                    "off",
                    cli_dest="transformer_cache_quantize",
                    choices=TRANSFORMER_CACHE_QUANTIZE_CHOICES,
                    choice_help=(
                        ("off", "Keep transformer caches in their source precision"),
                        ("mxfp8-blocks", "Quantize transformer block caches to MXFP8"),
                        (
                            "mxfp8-blocks-pretranspose",
                            "Quantize and pretranspose transformer block caches",
                        ),
                    ),
                ),
                F(
                    "video_ff_quantize_specs",
                    "Configure targeted video feed-forward quantization",
                    ("unique feed-forward targets using affine, mxfp4, mxfp8, or nvfp4"),
                    (),
                    cli_dest="video_ff_quantize_specs",
                ),
                F(
                    "video_ff_quantize_layers",
                    "Choose video layers for targeted quantization",
                    "unique integers from 0 through 47",
                    (),
                    cli_dest="video_ff_quantize_layers",
                ),
                F(
                    "video_ff_quantize_group_size",
                    "Set the targeted quantization group size",
                    "a positive integer when quantization specs are present",
                    64,
                    cli_dest="video_ff_quantize_group_size",
                ),
                F(
                    "video_ff_quantize_bits",
                    "Set the affine target bit count",
                    "a positive integer when quantization specs are present",
                    4,
                    cli_dest="video_ff_quantize_bits",
                ),
                F(
                    "stream_transformer",
                    "Use the bounded-residency transformer preset",
                    "true or false",
                    False,
                    cli_dest="stream_transformer",
                ),
                F(
                    "transformer_resident_blocks",
                    "Set the number of resident transformer blocks",
                    "an integer from 1 through 48",
                    STREAM_TRANSFORMER_RESIDENT_BLOCKS,
                    cli_dest="transformer_resident_blocks",
                    default_text=(f"unset, or {STREAM_TRANSFORMER_RESIDENT_BLOCKS} when streaming"),
                ),
                F(
                    "transformer_compile_group_size",
                    "Set the compiled transformer group size",
                    "a positive integer no greater than the resident block count",
                    STREAM_TRANSFORMER_COMPILE_GROUP_SIZE,
                    cli_dest="transformer_compile_group_size",
                    default_text=(f"unset, up to {STREAM_TRANSFORMER_COMPILE_GROUP_SIZE}"),
                ),
                F(
                    "compile_block_groups",
                    "Set the number of block groups to compile",
                    "an integer from 1 through 48",
                    48,
                    cli_dest="compile_block_groups",
                ),
            ),
        ),
        ConfigTableSpec(
            path=("model_artifacts",),
            record=LTX2ArtifactConfig,
            fields=(
                F(
                    "save_latents",
                    "Save stage-1 and final latents",
                    "true or false",
                    True,
                    cli_dest="save_latents",
                    default_text="unset, which inherits the save-all setting",
                ),
                F(
                    "save_media_conditioning",
                    "Save encoded media conditions",
                    "true or false",
                    True,
                    cli_dest="save_media_conditioning",
                    default_text="unset, which inherits the save-all setting",
                ),
                F(
                    "save_text_conditioning",
                    "Save prompt tensors and their mask",
                    "true or false",
                    True,
                    cli_dest="save_text_conditioning",
                    default_text="unset, which inherits the save-all setting",
                ),
            ),
        ),
        ConfigTableSpec(
            path=("restart",),
            record=RestartConfig,
            default_present=False,
            fields=(
                F(
                    "run",
                    "Load a prior run record",
                    "a completed KinoMLX run-log path",
                    Path("previous_run.json"),
                    cli_dest="restart_run",
                    default_text="unset, which starts a fresh run",
                ),
                F(
                    "phase",
                    "Select the first station to repeat",
                    "",
                    "decode",
                    cli_dest="restart_phase",
                    choices=RESTART_PHASE_CHOICES,
                    choice_help=(
                        ("decode", "Decode an already generated latent"),
                        ("stage-2", "Resume at the second denoising stage"),
                    ),
                ),
                F(
                    "latent_stage",
                    "Select the saved latent used for decode",
                    "",
                    "final",
                    cli_dest="latent_stage",
                    choices=LATENT_STAGE_CHOICES,
                    choice_help=(
                        ("final", "Decode the saved final latent"),
                        ("stage-1", "Decode the saved stage-1 latent"),
                    ),
                    default_text='"final" when the restart phase is decode',
                ),
                F(
                    "latents",
                    "Substitute a latent artifact",
                    "a path to a compatible safetensors file",
                    Path("edited.safetensors"),
                    cli_dest="restart_latents",
                    default_text="the artifact recorded in the run log",
                ),
            ),
        ),
    ),
    implications=(
        ConfigImplication(
            trigger=("output", "save_all_sidecars"),
            trigger_value=True,
            implied=(
                (("output", "save_run_log"), True),
                (("output", "save_console_log"), True),
                (("output", "save_effective_config"), True),
                (("output", "save_audio_sidecar"), True),
                (("output", "vsr_save_original"), True),
            ),
            expand_in_layers=True,
            excluded=(
                ("output", "save_hdr_heic_frames"),
                ("output", "save_vae_frames"),
            ),
            coverage_group=ConfigGroup.SAVE_ALL_CANDIDATE,
        ),
        ConfigImplication(
            trigger=("model_settings", "stream_transformer"),
            trigger_value=True,
            implied=(
                (
                    ("model_settings", "transformer_resident_blocks"),
                    STREAM_TRANSFORMER_RESIDENT_BLOCKS,
                ),
                (
                    ("model_settings", "transformer_compile_group_size"),
                    STREAM_TRANSFORMER_COMPILE_GROUP_SIZE,
                ),
            ),
        ),
    ),
)


__all__ = ["CONFIG_SCHEMA"]
