"""Model-neutral media contracts shared by generators and terminal sinks."""

from .frames import CloseableVideoFrameStream, VideoFrameStream
from .signals import (
    BT709_SDR_420_DELIVERY,
    BT709_SDR_422_DELIVERY,
    BT709_SDR_DELIVERY,
    BT2020_HLG_DELIVERY,
    ChromaSubsampling,
    ColorMatrix,
    ColorPrimaries,
    ColorRange,
    ColorTransfer,
    EncodedVideoDeliverySpec,
    ExrDeliverySpec,
    ExrSampleType,
    OutputColorPlan,
    UnsupportedSignalError,
    VideoCodec,
    VideoCodecProfile,
    VideoDeliverySpec,
    VideoLayout,
    VideoSignalSpec,
    VideoValueDomain,
    validate_encoded_delivery,
    validate_hlg_delivery,
    validate_sdr_delivery,
    validate_sdr_output_plan,
)

__all__ = [
    "BT2020_HLG_DELIVERY",
    "BT709_SDR_420_DELIVERY",
    "BT709_SDR_422_DELIVERY",
    "BT709_SDR_DELIVERY",
    "ChromaSubsampling",
    "CloseableVideoFrameStream",
    "ColorMatrix",
    "ColorPrimaries",
    "ColorRange",
    "ColorTransfer",
    "EncodedVideoDeliverySpec",
    "ExrDeliverySpec",
    "ExrSampleType",
    "OutputColorPlan",
    "UnsupportedSignalError",
    "VideoCodec",
    "VideoCodecProfile",
    "VideoDeliverySpec",
    "VideoFrameStream",
    "VideoLayout",
    "VideoSignalSpec",
    "VideoValueDomain",
    "validate_sdr_delivery",
    "validate_encoded_delivery",
    "validate_hlg_delivery",
    "validate_sdr_output_plan",
]
